#!/usr/bin/env bash
# 1.0 8/21/23 - This Script Tests the Local Password for the User - Cody K

user=$(ls -l /dev/console | awk '{ print $3 }')
pass=$(osascript -e 'display dialog "Please Enter Your Password to Verify You Know It:" default answer "" with title "RDT&E Password Tester" giving up after 60 with text buttons {"Authenticate"} default button 1 with hidden answer' -e 'return text returned of result')
attempts=1
until dscl . authonly "$user" "$pass" &>/dev/null ; do
	# lines 9 and 10 are only necessary if you wish to display no. of attempts remaining before failure
	attemptsRemaining=$(( 4 - attempts ))
	[[ $attemptsRemaining -eq 1 ]] && s= || s=s
	pass=$(osascript -e 'display dialog "Incorrect password entered, please try again. ('"$attemptsRemaining"' attempt'"$s"' remaining)" default answer "" with title "RDT&E Password Tester" giving up after 60 with text buttons {"Authenticate"} default button 1 with hidden answer' -e 'return text returned of result')
	let attempts++
	(( attempts > 3 )) && exit 0
done
(osascript -e 'display dialog "Password Entered Correctly, CONGRATS \n \nPasswords Must Be Changed Every 60 Days To Avoid A Complete System Lockout" with title "RDT&E Password Tester" giving up after 60 with text buttons {"Close"} default button 1 with hidden answer' &>/dev/null)  

exit 0
