#!/bin/bash
#CMK WRITTEN 2/26/2019

sudo /Applications/Adobe\ Acrobat\ 2015/Adobe\ Acrobat.app/Contents/Helpers/Acrobat\ Uninstaller.app/Contents/Library/LaunchServices/com.adobe.Acrobat.RemoverTool /Applications/Adobe\ Acrobat\ 2015/Adobe\ Acrobat.app

Exit 0
